Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/trusty64"
	config.vm.network "public_network"

	# Disable default synced folder to better simulate actual hardware.
	config.vm.synced_folder '.', '/vagrant', disabled: true

	config.vm.provision "shell", inline: <<-SHELL
		# Update
		apt-get update -y

		# Unison
		add-apt-repository ppa:eugenesan/ppa
		sudo apt-get update
		sudo apt-get install unison

		# Python
		apt-get install git python-pip python-dev -y
		pip install ptyprocess

		# Builder
		git clone https://github.com/buildernetwork/builder-python
		pip install builder-python/builder

		# Builder Environment
		mkdir /builder && chown vagrant /builder
	SHELL
	config.vm.provision "shell", privileged: false, inline: <<-SHELL
		cd /builder
		builder init %NAME%
		# builder start manager
		builder start manager
	SHELL
end
